version: '3'

services:
  stac:
    container_name: delta.stac
    platform: linux/amd64
    build:
      context: .
      dockerfile: local/Dockerfile.stac
    ports:
      - "8081:8081"
    environment:
      - APP_HOST=0.0.0.0
      - APP_PORT=8081
      - HOST=0.0.0.0
      - PORT=8081
      - ENVIRONMENT=local
      - POSTGRES_USER=username
      - POSTGRES_PASS=password
      - POSTGRES_DBNAME=postgis
      - POSTGRES_HOST_READER=database
      - POSTGRES_HOST_WRITER=database
      - POSTGRES_PORT=5432
      - DB_MIN_CONN_SIZE=1
      - DB_MAX_CONN_SIZE=10
      - WEB_CONCURRENCY=10
      - MODULE_NAME=delta.stac.app
      - VARIABLE_NAME=app
      - TITILER_ENDPOINT=raster
    depends_on:
      - database
      - raster

  raster:
    container_name: delta.raster
    platform: linux/amd64
    build:
      context: .
      dockerfile: local/Dockerfile.raster
    ports:
      - "8082:8082"
    environment:
      - HOST=0.0.0.0
      - PORT=8082
      - APP_HOST=0.0.0.0
      - APP_PORT=8082
      - ENVIRONMENT=local
      - POSTGRES_USER=username
      - POSTGRES_PASS=password
      - POSTGRES_DBNAME=postgis
      - POSTGRES_HOST_READER=database
      - POSTGRES_HOST_WRITER=database
      - POSTGRES_PORT=5432
      - DB_MIN_CONN_SIZE=1
      - DB_MAX_CONN_SIZE=5
      - WEB_CONCURRENCY=5
      # - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      # - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - CPL_TMPDIR=/tmp
      - GDAL_CACHEMAX=75%
      - GDAL_DISABLE_READDIR_ON_OPEN=EMPTY_DIR
      - GDAL_HTTP_MERGE_CONSECUTIVE_RANGES=YES
      - GDAL_HTTP_MULTIPLEX=YES
      - GDAL_HTTP_VERSION=2
      - PYTHONWARNINGS=ignore
      - VSI_CACHE=TRUE
      - VSI_CACHE_SIZE=536870912
      - WORKERS_PER_CORE=1
      - MOSAIC_CONCURRENCY=1
      - AWS_PROFILE=${AWS_PROFILE}
    volumes:
      - $HOME/.aws/credentials:/root/.aws/credentials
    depends_on:
      - database

  database:
    container_name: delta.db
    platform: linux/amd64
    image: ghcr.io/stac-utils/pgstac:v0.3.6
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgis
      - PGUSER=username
      - PGPASSWORD=password
      - PGHOST=localhost
      - PGDATABASE=postgis
    ports:
      - "5439:5432"
    command: postgres -N 500

networks:
  default:
    name: delta-network
