name: Pull Request - Lint and Test Workflow

permissions:
  id-token: write
  contents: read

on: [pull_request]

jobs:
  gitflow-enforcer:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        if: github.base_ref == 'main' && github.head_ref != 'dev' || github.base_ref == 'production' && github.head_ref != 'main'
        run: |
          echo "ERROR: You can only merge to main from dev and to production from main"
          exit 1

  lint:
    runs-on: ubuntu-latest
    needs: [gitflow-enforcer]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
    
      - uses: actions/cache@v3
        with:
          path: ${{ env.pythonLocation }}
          key:  ${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e  .[dev,deploy,test]

      - name: Run pre-commit
        run: pre-commit run --all-files

  test:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.DEPLOYMENT_ROLE_ARN }}
          role-session-name: "ghgc-backend-github-action"
          aws-region: "us-west-2"

      - name: Launch services
        run: |
          docker-compose up --build -d stac raster

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
    
      - uses: actions/cache@v3
        with:
          path: ${{ env.pythonLocation }}
          key:  ${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .[dev,deploy,test]

      - name: Ingest Stac Items/Collection
        run: |
          pypgstac pgready --dsn postgresql://username:password@0.0.0.0:5432/postgis
          pypgstac load collections .github/workflows/data/noaa-emergency-response.json --dsn postgresql://username:password@0.0.0.0:5432/postgis --method insert
          pypgstac load items .github/workflows/data/noaa-eri-nashville2020.json --dsn postgresql://username:password@0.0.0.0:5432/postgis --method insert

      - name: Sleep for 10 seconds
        run: sleep 10s
        shell: bash

      - name: Integrations tests
        run: python -m pytest .github/workflows/tests/ -vv -s

      - name: Stop services
        run: docker-compose stop

  predeploy:
    needs: [test]
    environment: development
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.DEPLOYMENT_ROLE_ARN }}
          role-session-name: "ghgc-backend-github-action"
          aws-region: "us-west-2"

      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install CDK
        run: npm install -g aws-cdk@2

      - uses: actions/cache@v3
        with:
          path: ${{ env.pythonLocation }}
          key:  ${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .[dev,deploy,test]

      - name: Get environment configuration for develop branch
        run: ./scripts/get-env.sh ${{ secrets.ENV_AWS_SECRET_NAME }}

      - name: Pre deployment CDK diff
        run: |
          echo $STAGE
          cdk diff --all
